### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by adiracu** [overbase/overbase#1]
Hei Rosty!  

I'm trying to start a side business and after multiple discussions came up with the name "overbase", but I just saw that you already created that organization on GitHub 1 year ago. 🙈 Great minds think alike! :)   

Any chance you can give me the organisation or do you still have plans for it?    

Cheers, 
Adi

**Comment by rostyslav** [comment]
Hi Adi,

Project is a bit on hold because of war, but definitely I'm planning to continue my work on it.

Regards,
Rostyslav

**Comment by adiracu** [comment]
Any possibility you can continue your work under a different name? I'm open to paying $500 for it.

**Comment by rostyslav** [comment]
Without any doubt this name will be used for future project development.

**Comment by adiracu** [comment]
Do you also have a domain name for it?

**Comment by adiracu** [comment]
I see you're a bit attached to this name. If you could explain the product to me, I might help you find a better name. Atm, the code is super minimal, can't make sense of what it's supposed to do. 

Have a think about my offer and let me know if you change your mind. I'll have a look around for other names until then.

Cheers and all the best to you and Ukraine!

**Comment by rostyslav** [comment]
Thank you for understanding. Best wishes to you and your project.
